In [74]:
import cvxpy as cp
import numpy as np

from readup import readup


In [61]:
np.random.randn(m, n)

array([[ 0.16003707,  0.87616892,  0.31563495, -2.02220122, -0.30620401,
         0.82797464,  0.23009474,  0.76201118],
       [-0.22232814, -0.20075807,  0.18656139,  0.41005165,  0.19829972,
         0.11900865, -0.67066229,  0.37756379],
       [ 0.12182127,  1.12948391,  1.19891788,  0.18515642, -0.37528495,
        -0.63873041,  0.42349435,  0.07734007],
       [-0.34385368,  0.04359686, -0.62000084,  0.69803203, -0.44712856,
         1.2245077 ,  0.40349164,  0.59357852]])

In [78]:
up = readup('/home/puneet/Projects/minedgerolemining/irreducible.txt')

nedges = 0
users = set()
perms = set()
for u in up:
    users.add(u)
    perms = perms.union(up[u])
    nedges += len(up[u])

print('Total # users:', len(users))
print('Total # perms:', len(perms))
print('Total # edges:', nedges)
sys.stdout.flush()

UP map written to /home/puneet/Projects/minedgerolemining/irreducible.txt-upmap.txt
Total # users: 5
Total # perms: 5
Total # edges: 15


In [84]:
x = cp.Variable((5,5), symmetric=False)
x

Variable((5, 5), var536)

In [73]:
m = 4
n = 8
p = 5

np.random.seed(1)

P = np.random.randn(n, n)
P = np.array([])

C = set()
D = set()
for r in range(nedges):
    for u in up:
        C_ur = cp.Variable(n)
        C.add(C_ur)
        
    for p in perms:
        D_rp = cp.Variable(n)
        D.add(D_rp)

for u in up:
    

P = P.T @ P

q = np.random.randn(n)
# q = np.array([1,2,3,4,5,6,7,8])
G = np.random.randn(m, n)
h = G @ np.random.randn(n)
print(h)
A = np.random.randn(p, n)
b = np.random.randn(p)

[ 2.16823026  0.9474987   0.29115668 -0.94898404]


In [72]:
X = cp.Variable(n)
X

Variable((8,), var530)

In [67]:
# Print result.
print("\nThe optimal value is", prob.value)
print("A solution x is")
print(x.value)
print("A dual solution corresponding to the inequality constraints is")
print(prob.constraints[0].dual_value)


The optimal value is 8.906871865383419
A solution x is
[ 0.19603243 -0.77805752 -0.49748141  0.72721921 -2.8414542  -1.77549613
 -1.33050117 -0.37612288]
A dual solution corresponding to the inequality constraints is
[0.         0.         3.73635273 2.91208846]
